# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from copley/cmd2switch_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import copley.msg
import std_msgs.msg

class cmd2switch_msg(genpy.Message):
  _md5sum = "19a90ae0a917ebed802b29fa446ac872"
  _type = "copley/cmd2switch_msg"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# -*- coding:utf-8 -*-
# $ catkin_make -DCATKIN_WHITELIST_PACKAGES="copley"
# 用于控制钩刺机构和推拉机构的运动
# Header
Header header
# Switch
int8 adjust_left
int8 adjust_right
bool enc_wing
bool enc_sting
copley/motor_msg wing
copley/motor_msg sting
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: copley/motor_msg
# -*- coding:utf-8 -*-
# $ catkin_make -DCATKIN_WHITELIST_PACKAGES="copley"

# Control
float32 motor_l
float32 motor_r"""
  __slots__ = ['header','adjust_left','adjust_right','enc_wing','enc_sting','wing','sting']
  _slot_types = ['std_msgs/Header','int8','int8','bool','bool','copley/motor_msg','copley/motor_msg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,adjust_left,adjust_right,enc_wing,enc_sting,wing,sting

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cmd2switch_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.adjust_left is None:
        self.adjust_left = 0
      if self.adjust_right is None:
        self.adjust_right = 0
      if self.enc_wing is None:
        self.enc_wing = False
      if self.enc_sting is None:
        self.enc_sting = False
      if self.wing is None:
        self.wing = copley.msg.motor_msg()
      if self.sting is None:
        self.sting = copley.msg.motor_msg()
    else:
      self.header = std_msgs.msg.Header()
      self.adjust_left = 0
      self.adjust_right = 0
      self.enc_wing = False
      self.enc_sting = False
      self.wing = copley.msg.motor_msg()
      self.sting = copley.msg.motor_msg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2b2B4f().pack(_x.adjust_left, _x.adjust_right, _x.enc_wing, _x.enc_sting, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.wing is None:
        self.wing = copley.msg.motor_msg()
      if self.sting is None:
        self.sting = copley.msg.motor_msg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.adjust_left, _x.adjust_right, _x.enc_wing, _x.enc_sting, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r,) = _get_struct_2b2B4f().unpack(str[start:end])
      self.enc_wing = bool(self.enc_wing)
      self.enc_sting = bool(self.enc_sting)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2b2B4f().pack(_x.adjust_left, _x.adjust_right, _x.enc_wing, _x.enc_sting, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.wing is None:
        self.wing = copley.msg.motor_msg()
      if self.sting is None:
        self.sting = copley.msg.motor_msg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.adjust_left, _x.adjust_right, _x.enc_wing, _x.enc_sting, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r,) = _get_struct_2b2B4f().unpack(str[start:end])
      self.enc_wing = bool(self.enc_wing)
      self.enc_sting = bool(self.enc_sting)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b2B4f = None
def _get_struct_2b2B4f():
    global _struct_2b2B4f
    if _struct_2b2B4f is None:
        _struct_2b2B4f = struct.Struct("<2b2B4f")
    return _struct_2b2B4f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
