# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from copley/motors_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import copley.msg

class motors_msg(genpy.Message):
  _md5sum = "e82ee222b0e96a1635070adf737cc004"
  _type = "copley/motors_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# -*- coding:utf-8 -*-
# $ catkin_make -DCATKIN_WHITELIST_PACKAGES="copley"

copley/motor_msg drive
copley/motor_msg wing
copley/motor_msg sting
================================================================================
MSG: copley/motor_msg
# -*- coding:utf-8 -*-
# $ catkin_make -DCATKIN_WHITELIST_PACKAGES="copley"

# Control
float32 motor_l
float32 motor_r"""
  __slots__ = ['drive','wing','sting']
  _slot_types = ['copley/motor_msg','copley/motor_msg','copley/motor_msg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       drive,wing,sting

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motors_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.drive is None:
        self.drive = copley.msg.motor_msg()
      if self.wing is None:
        self.wing = copley.msg.motor_msg()
      if self.sting is None:
        self.sting = copley.msg.motor_msg()
    else:
      self.drive = copley.msg.motor_msg()
      self.wing = copley.msg.motor_msg()
      self.sting = copley.msg.motor_msg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.drive.motor_l, _x.drive.motor_r, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.drive is None:
        self.drive = copley.msg.motor_msg()
      if self.wing is None:
        self.wing = copley.msg.motor_msg()
      if self.sting is None:
        self.sting = copley.msg.motor_msg()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.drive.motor_l, _x.drive.motor_r, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.drive.motor_l, _x.drive.motor_r, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.drive is None:
        self.drive = copley.msg.motor_msg()
      if self.wing is None:
        self.wing = copley.msg.motor_msg()
      if self.sting is None:
        self.sting = copley.msg.motor_msg()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.drive.motor_l, _x.drive.motor_r, _x.wing.motor_l, _x.wing.motor_r, _x.sting.motor_l, _x.sting.motor_r,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
