# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from copley/ucr_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import copley.msg
import std_msgs.msg

class ucr_msg(genpy.Message):
  _md5sum = "697cf9df9ce516a16d261952c472d294"
  _type = "copley/ucr_msg"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# -*- coding:utf-8 -*-
# $ catkin_make -DCATKIN_WHITELIST_PACKAGES="copley"

# Header
Header header
# Drive
copley/motors_msg current
copley/motors_msg velocity
copley/motors_msg position

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: copley/motors_msg
# -*- coding:utf-8 -*-
# $ catkin_make -DCATKIN_WHITELIST_PACKAGES="copley"

copley/motor_msg drive
copley/motor_msg wing
copley/motor_msg sting
================================================================================
MSG: copley/motor_msg
# -*- coding:utf-8 -*-
# $ catkin_make -DCATKIN_WHITELIST_PACKAGES="copley"

# Control
float32 motor_l
float32 motor_r"""
  __slots__ = ['header','current','velocity','position']
  _slot_types = ['std_msgs/Header','copley/motors_msg','copley/motors_msg','copley/motors_msg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,current,velocity,position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ucr_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.current is None:
        self.current = copley.msg.motors_msg()
      if self.velocity is None:
        self.velocity = copley.msg.motors_msg()
      if self.position is None:
        self.position = copley.msg.motors_msg()
    else:
      self.header = std_msgs.msg.Header()
      self.current = copley.msg.motors_msg()
      self.velocity = copley.msg.motors_msg()
      self.position = copley.msg.motors_msg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18f().pack(_x.current.drive.motor_l, _x.current.drive.motor_r, _x.current.wing.motor_l, _x.current.wing.motor_r, _x.current.sting.motor_l, _x.current.sting.motor_r, _x.velocity.drive.motor_l, _x.velocity.drive.motor_r, _x.velocity.wing.motor_l, _x.velocity.wing.motor_r, _x.velocity.sting.motor_l, _x.velocity.sting.motor_r, _x.position.drive.motor_l, _x.position.drive.motor_r, _x.position.wing.motor_l, _x.position.wing.motor_r, _x.position.sting.motor_l, _x.position.sting.motor_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.current is None:
        self.current = copley.msg.motors_msg()
      if self.velocity is None:
        self.velocity = copley.msg.motors_msg()
      if self.position is None:
        self.position = copley.msg.motors_msg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.current.drive.motor_l, _x.current.drive.motor_r, _x.current.wing.motor_l, _x.current.wing.motor_r, _x.current.sting.motor_l, _x.current.sting.motor_r, _x.velocity.drive.motor_l, _x.velocity.drive.motor_r, _x.velocity.wing.motor_l, _x.velocity.wing.motor_r, _x.velocity.sting.motor_l, _x.velocity.sting.motor_r, _x.position.drive.motor_l, _x.position.drive.motor_r, _x.position.wing.motor_l, _x.position.wing.motor_r, _x.position.sting.motor_l, _x.position.sting.motor_r,) = _get_struct_18f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18f().pack(_x.current.drive.motor_l, _x.current.drive.motor_r, _x.current.wing.motor_l, _x.current.wing.motor_r, _x.current.sting.motor_l, _x.current.sting.motor_r, _x.velocity.drive.motor_l, _x.velocity.drive.motor_r, _x.velocity.wing.motor_l, _x.velocity.wing.motor_r, _x.velocity.sting.motor_l, _x.velocity.sting.motor_r, _x.position.drive.motor_l, _x.position.drive.motor_r, _x.position.wing.motor_l, _x.position.wing.motor_r, _x.position.sting.motor_l, _x.position.sting.motor_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.current is None:
        self.current = copley.msg.motors_msg()
      if self.velocity is None:
        self.velocity = copley.msg.motors_msg()
      if self.position is None:
        self.position = copley.msg.motors_msg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.current.drive.motor_l, _x.current.drive.motor_r, _x.current.wing.motor_l, _x.current.wing.motor_r, _x.current.sting.motor_l, _x.current.sting.motor_r, _x.velocity.drive.motor_l, _x.velocity.drive.motor_r, _x.velocity.wing.motor_l, _x.velocity.wing.motor_r, _x.velocity.sting.motor_l, _x.velocity.sting.motor_r, _x.position.drive.motor_l, _x.position.drive.motor_r, _x.position.wing.motor_l, _x.position.wing.motor_r, _x.position.sting.motor_l, _x.position.sting.motor_r,) = _get_struct_18f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18f = None
def _get_struct_18f():
    global _struct_18f
    if _struct_18f is None:
        _struct_18f = struct.Struct("<18f")
    return _struct_18f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
