# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sensor/bme280.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class bme280(genpy.Message):
  _md5sum = "cf334dd156db771a2125cf250be13097"
  _type = "sensor/bme280"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# defain environment sensor bme280 message format
# ID
int8 chip_id
int8 chip_version
# temperature
float32 temperature
# air pressure
float32 pressure
# humidity
float32 humidity"""
  __slots__ = ['chip_id','chip_version','temperature','pressure','humidity']
  _slot_types = ['int8','int8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       chip_id,chip_version,temperature,pressure,humidity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bme280, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.chip_id is None:
        self.chip_id = 0
      if self.chip_version is None:
        self.chip_version = 0
      if self.temperature is None:
        self.temperature = 0.
      if self.pressure is None:
        self.pressure = 0.
      if self.humidity is None:
        self.humidity = 0.
    else:
      self.chip_id = 0
      self.chip_version = 0
      self.temperature = 0.
      self.pressure = 0.
      self.humidity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2b3f().pack(_x.chip_id, _x.chip_version, _x.temperature, _x.pressure, _x.humidity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.chip_id, _x.chip_version, _x.temperature, _x.pressure, _x.humidity,) = _get_struct_2b3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2b3f().pack(_x.chip_id, _x.chip_version, _x.temperature, _x.pressure, _x.humidity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.chip_id, _x.chip_version, _x.temperature, _x.pressure, _x.humidity,) = _get_struct_2b3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b3f = None
def _get_struct_2b3f():
    global _struct_2b3f
    if _struct_2b3f is None:
        _struct_2b3f = struct.Struct("<2b3f")
    return _struct_2b3f
