# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sensor/power_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class power_msg(genpy.Message):
  _md5sum = "6985abf14ffd1aad6747673ddb5719f6"
  _type = "sensor/power_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 定义一个4维向量用于传输电量的数据
float32 remaining
int16 consumed
float32 capacity
float32 percentage"""
  __slots__ = ['remaining','consumed','capacity','percentage']
  _slot_types = ['float32','int16','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       remaining,consumed,capacity,percentage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(power_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.remaining is None:
        self.remaining = 0.
      if self.consumed is None:
        self.consumed = 0
      if self.capacity is None:
        self.capacity = 0.
      if self.percentage is None:
        self.percentage = 0.
    else:
      self.remaining = 0.
      self.consumed = 0
      self.capacity = 0.
      self.percentage = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fh2f().pack(_x.remaining, _x.consumed, _x.capacity, _x.percentage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.remaining, _x.consumed, _x.capacity, _x.percentage,) = _get_struct_fh2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fh2f().pack(_x.remaining, _x.consumed, _x.capacity, _x.percentage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.remaining, _x.consumed, _x.capacity, _x.percentage,) = _get_struct_fh2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fh2f = None
def _get_struct_fh2f():
    global _struct_fh2f
    if _struct_fh2f is None:
        _struct_fh2f = struct.Struct("<fh2f")
    return _struct_fh2f
