// Generated by gencpp from file copley/cmd2start_msg.msg
// DO NOT EDIT!


#ifndef COPLEY_MESSAGE_CMD2START_MSG_H
#define COPLEY_MESSAGE_CMD2START_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace copley
{
template <class ContainerAllocator>
struct cmd2start_msg_
{
  typedef cmd2start_msg_<ContainerAllocator> Type;

  cmd2start_msg_()
    : header()
    , rpi_host(0)
    , copley_motor(0)  {
    }
  cmd2start_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rpi_host(0)
    , copley_motor(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _rpi_host_type;
  _rpi_host_type rpi_host;

   typedef int16_t _copley_motor_type;
  _copley_motor_type copley_motor;





  typedef boost::shared_ptr< ::copley::cmd2start_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::copley::cmd2start_msg_<ContainerAllocator> const> ConstPtr;

}; // struct cmd2start_msg_

typedef ::copley::cmd2start_msg_<std::allocator<void> > cmd2start_msg;

typedef boost::shared_ptr< ::copley::cmd2start_msg > cmd2start_msgPtr;
typedef boost::shared_ptr< ::copley::cmd2start_msg const> cmd2start_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::copley::cmd2start_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::copley::cmd2start_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::copley::cmd2start_msg_<ContainerAllocator1> & lhs, const ::copley::cmd2start_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rpi_host == rhs.rpi_host &&
    lhs.copley_motor == rhs.copley_motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::copley::cmd2start_msg_<ContainerAllocator1> & lhs, const ::copley::cmd2start_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace copley

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::copley::cmd2start_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::copley::cmd2start_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::cmd2start_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::cmd2start_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::cmd2start_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::cmd2start_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::copley::cmd2start_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "111b1a1fda8851b8a4f1107ff12e3c61";
  }

  static const char* value(const ::copley::cmd2start_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x111b1a1fda8851b8ULL;
  static const uint64_t static_value2 = 0xa4f1107ff12e3c61ULL;
};

template<class ContainerAllocator>
struct DataType< ::copley::cmd2start_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "copley/cmd2start_msg";
  }

  static const char* value(const ::copley::cmd2start_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::copley::cmd2start_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# $ catkin_make -DCATKIN_WHITELIST_PACKAGES=\"copley\"\n"
"\n"
"# Header\n"
"Header header\n"
"# Start_Joy\n"
"int16 rpi_host\n"
"int16 copley_motor # 采用int变量而不是bool，可能再分出第三种情况，如重启\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::copley::cmd2start_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::copley::cmd2start_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rpi_host);
      stream.next(m.copley_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd2start_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::copley::cmd2start_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::copley::cmd2start_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rpi_host: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rpi_host);
    s << indent << "copley_motor: ";
    Printer<int16_t>::stream(s, indent + "  ", v.copley_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COPLEY_MESSAGE_CMD2START_MSG_H
