// Generated by gencpp from file copley/cmd2drive_msg.msg
// DO NOT EDIT!


#ifndef COPLEY_MESSAGE_CMD2DRIVE_MSG_H
#define COPLEY_MESSAGE_CMD2DRIVE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <copley/motor_msg.h>

namespace copley
{
template <class ContainerAllocator>
struct cmd2drive_msg_
{
  typedef cmd2drive_msg_<ContainerAllocator> Type;

  cmd2drive_msg_()
    : header()
    , drive()  {
    }
  cmd2drive_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drive(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::copley::motor_msg_<ContainerAllocator>  _drive_type;
  _drive_type drive;





  typedef boost::shared_ptr< ::copley::cmd2drive_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::copley::cmd2drive_msg_<ContainerAllocator> const> ConstPtr;

}; // struct cmd2drive_msg_

typedef ::copley::cmd2drive_msg_<std::allocator<void> > cmd2drive_msg;

typedef boost::shared_ptr< ::copley::cmd2drive_msg > cmd2drive_msgPtr;
typedef boost::shared_ptr< ::copley::cmd2drive_msg const> cmd2drive_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::copley::cmd2drive_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::copley::cmd2drive_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::copley::cmd2drive_msg_<ContainerAllocator1> & lhs, const ::copley::cmd2drive_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drive == rhs.drive;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::copley::cmd2drive_msg_<ContainerAllocator1> & lhs, const ::copley::cmd2drive_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace copley

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::copley::cmd2drive_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::copley::cmd2drive_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::cmd2drive_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::cmd2drive_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::cmd2drive_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::cmd2drive_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::copley::cmd2drive_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49b69f086ac244e027a573abc129a395";
  }

  static const char* value(const ::copley::cmd2drive_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49b69f086ac244e0ULL;
  static const uint64_t static_value2 = 0x27a573abc129a395ULL;
};

template<class ContainerAllocator>
struct DataType< ::copley::cmd2drive_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "copley/cmd2drive_msg";
  }

  static const char* value(const ::copley::cmd2drive_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::copley::cmd2drive_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# -*- coding:utf-8 -*-\n"
"# $ catkin_make -DCATKIN_WHITELIST_PACKAGES=\"copley\"\n"
"\n"
"# Header\n"
"Header header\n"
"# Drive\n"
"copley/motor_msg drive\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: copley/motor_msg\n"
"# -*- coding:utf-8 -*-\n"
"# $ catkin_make -DCATKIN_WHITELIST_PACKAGES=\"copley\"\n"
"\n"
"# Control\n"
"float32 motor_l\n"
"float32 motor_r\n"
;
  }

  static const char* value(const ::copley::cmd2drive_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::copley::cmd2drive_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd2drive_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::copley::cmd2drive_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::copley::cmd2drive_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drive: ";
    s << std::endl;
    Printer< ::copley::motor_msg_<ContainerAllocator> >::stream(s, indent + "  ", v.drive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COPLEY_MESSAGE_CMD2DRIVE_MSG_H
