// Generated by gencpp from file copley/enc_msg.msg
// DO NOT EDIT!


#ifndef COPLEY_MESSAGE_ENC_MSG_H
#define COPLEY_MESSAGE_ENC_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace copley
{
template <class ContainerAllocator>
struct enc_msg_
{
  typedef enc_msg_<ContainerAllocator> Type;

  enc_msg_()
    : header()
    , motor_0(0.0)
    , motor_1(0.0)
    , motor_2(0.0)
    , motor_3(0.0)
    , motor_4(0.0)
    , motor_5(0.0)  {
    }
  enc_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor_0(0.0)
    , motor_1(0.0)
    , motor_2(0.0)
    , motor_3(0.0)
    , motor_4(0.0)
    , motor_5(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _motor_0_type;
  _motor_0_type motor_0;

   typedef float _motor_1_type;
  _motor_1_type motor_1;

   typedef float _motor_2_type;
  _motor_2_type motor_2;

   typedef float _motor_3_type;
  _motor_3_type motor_3;

   typedef float _motor_4_type;
  _motor_4_type motor_4;

   typedef float _motor_5_type;
  _motor_5_type motor_5;





  typedef boost::shared_ptr< ::copley::enc_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::copley::enc_msg_<ContainerAllocator> const> ConstPtr;

}; // struct enc_msg_

typedef ::copley::enc_msg_<std::allocator<void> > enc_msg;

typedef boost::shared_ptr< ::copley::enc_msg > enc_msgPtr;
typedef boost::shared_ptr< ::copley::enc_msg const> enc_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::copley::enc_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::copley::enc_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::copley::enc_msg_<ContainerAllocator1> & lhs, const ::copley::enc_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motor_0 == rhs.motor_0 &&
    lhs.motor_1 == rhs.motor_1 &&
    lhs.motor_2 == rhs.motor_2 &&
    lhs.motor_3 == rhs.motor_3 &&
    lhs.motor_4 == rhs.motor_4 &&
    lhs.motor_5 == rhs.motor_5;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::copley::enc_msg_<ContainerAllocator1> & lhs, const ::copley::enc_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace copley

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::copley::enc_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::copley::enc_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::enc_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::enc_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::enc_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::enc_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::copley::enc_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a888e664d4832aa9d46846c07b169702";
  }

  static const char* value(const ::copley::enc_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa888e664d4832aa9ULL;
  static const uint64_t static_value2 = 0xd46846c07b169702ULL;
};

template<class ContainerAllocator>
struct DataType< ::copley::enc_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "copley/enc_msg";
  }

  static const char* value(const ::copley::enc_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::copley::enc_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# -*- coding:utf-8 -*-\n"
"# $ catkin_make -DCATKIN_WHITELIST_PACKAGES=\"copley\"\n"
"# 这个是用来读取多个电机的控制指令的数据\n"
"# 主要是为了方便， 暂时写了六个，不一定都用上，留作扩充，就是个数量问题\n"
"# 另外，编号按照node_id来编排\n"
"\n"
"# Header\n"
"Header header\n"
"# Control\n"
"float32 motor_0\n"
"float32 motor_1\n"
"float32 motor_2\n"
"float32 motor_3\n"
"float32 motor_4\n"
"float32 motor_5\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::copley::enc_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::copley::enc_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor_0);
      stream.next(m.motor_1);
      stream.next(m.motor_2);
      stream.next(m.motor_3);
      stream.next(m.motor_4);
      stream.next(m.motor_5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enc_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::copley::enc_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::copley::enc_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor_0: ";
    Printer<float>::stream(s, indent + "  ", v.motor_0);
    s << indent << "motor_1: ";
    Printer<float>::stream(s, indent + "  ", v.motor_1);
    s << indent << "motor_2: ";
    Printer<float>::stream(s, indent + "  ", v.motor_2);
    s << indent << "motor_3: ";
    Printer<float>::stream(s, indent + "  ", v.motor_3);
    s << indent << "motor_4: ";
    Printer<float>::stream(s, indent + "  ", v.motor_4);
    s << indent << "motor_5: ";
    Printer<float>::stream(s, indent + "  ", v.motor_5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COPLEY_MESSAGE_ENC_MSG_H
