// Generated by gencpp from file copley/ucr_msg.msg
// DO NOT EDIT!


#ifndef COPLEY_MESSAGE_UCR_MSG_H
#define COPLEY_MESSAGE_UCR_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <copley/motors_msg.h>
#include <copley/motors_msg.h>
#include <copley/motors_msg.h>

namespace copley
{
template <class ContainerAllocator>
struct ucr_msg_
{
  typedef ucr_msg_<ContainerAllocator> Type;

  ucr_msg_()
    : header()
    , current()
    , velocity()
    , position()  {
    }
  ucr_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current(_alloc)
    , velocity(_alloc)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::copley::motors_msg_<ContainerAllocator>  _current_type;
  _current_type current;

   typedef  ::copley::motors_msg_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::copley::motors_msg_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::copley::ucr_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::copley::ucr_msg_<ContainerAllocator> const> ConstPtr;

}; // struct ucr_msg_

typedef ::copley::ucr_msg_<std::allocator<void> > ucr_msg;

typedef boost::shared_ptr< ::copley::ucr_msg > ucr_msgPtr;
typedef boost::shared_ptr< ::copley::ucr_msg const> ucr_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::copley::ucr_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::copley::ucr_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::copley::ucr_msg_<ContainerAllocator1> & lhs, const ::copley::ucr_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.current == rhs.current &&
    lhs.velocity == rhs.velocity &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::copley::ucr_msg_<ContainerAllocator1> & lhs, const ::copley::ucr_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace copley

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::copley::ucr_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::copley::ucr_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::ucr_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copley::ucr_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::ucr_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copley::ucr_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::copley::ucr_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "697cf9df9ce516a16d261952c472d294";
  }

  static const char* value(const ::copley::ucr_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x697cf9df9ce516a1ULL;
  static const uint64_t static_value2 = 0x6d261952c472d294ULL;
};

template<class ContainerAllocator>
struct DataType< ::copley::ucr_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "copley/ucr_msg";
  }

  static const char* value(const ::copley::ucr_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::copley::ucr_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# -*- coding:utf-8 -*-\n"
"# $ catkin_make -DCATKIN_WHITELIST_PACKAGES=\"copley\"\n"
"\n"
"# Header\n"
"Header header\n"
"# Drive\n"
"copley/motors_msg current\n"
"copley/motors_msg velocity\n"
"copley/motors_msg position\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: copley/motors_msg\n"
"# -*- coding:utf-8 -*-\n"
"# $ catkin_make -DCATKIN_WHITELIST_PACKAGES=\"copley\"\n"
"\n"
"copley/motor_msg drive\n"
"copley/motor_msg wing\n"
"copley/motor_msg sting\n"
"================================================================================\n"
"MSG: copley/motor_msg\n"
"# -*- coding:utf-8 -*-\n"
"# $ catkin_make -DCATKIN_WHITELIST_PACKAGES=\"copley\"\n"
"\n"
"# Control\n"
"float32 motor_l\n"
"float32 motor_r\n"
;
  }

  static const char* value(const ::copley::ucr_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::copley::ucr_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current);
      stream.next(m.velocity);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ucr_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::copley::ucr_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::copley::ucr_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current: ";
    s << std::endl;
    Printer< ::copley::motors_msg_<ContainerAllocator> >::stream(s, indent + "  ", v.current);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::copley::motors_msg_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::copley::motors_msg_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COPLEY_MESSAGE_UCR_MSG_H
