// Generated by gencpp from file sensor/watt_msg.msg
// DO NOT EDIT!


#ifndef SENSOR_MESSAGE_WATT_MSG_H
#define SENSOR_MESSAGE_WATT_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor
{
template <class ContainerAllocator>
struct watt_msg_
{
  typedef watt_msg_<ContainerAllocator> Type;

  watt_msg_()
    : voltage(0.0)
    , current(0.0)
    , resistance(0.0)
    , watt(0.0)  {
    }
  watt_msg_(const ContainerAllocator& _alloc)
    : voltage(0.0)
    , current(0.0)
    , resistance(0.0)
    , watt(0.0)  {
  (void)_alloc;
    }



   typedef float _voltage_type;
  _voltage_type voltage;

   typedef float _current_type;
  _current_type current;

   typedef float _resistance_type;
  _resistance_type resistance;

   typedef float _watt_type;
  _watt_type watt;





  typedef boost::shared_ptr< ::sensor::watt_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor::watt_msg_<ContainerAllocator> const> ConstPtr;

}; // struct watt_msg_

typedef ::sensor::watt_msg_<std::allocator<void> > watt_msg;

typedef boost::shared_ptr< ::sensor::watt_msg > watt_msgPtr;
typedef boost::shared_ptr< ::sensor::watt_msg const> watt_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor::watt_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor::watt_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor::watt_msg_<ContainerAllocator1> & lhs, const ::sensor::watt_msg_<ContainerAllocator2> & rhs)
{
  return lhs.voltage == rhs.voltage &&
    lhs.current == rhs.current &&
    lhs.resistance == rhs.resistance &&
    lhs.watt == rhs.watt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor::watt_msg_<ContainerAllocator1> & lhs, const ::sensor::watt_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor::watt_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor::watt_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor::watt_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor::watt_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor::watt_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor::watt_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor::watt_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "136cc9f95f5d86898b1dfcc8b32f4a40";
  }

  static const char* value(const ::sensor::watt_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x136cc9f95f5d8689ULL;
  static const uint64_t static_value2 = 0x8b1dfcc8b32f4a40ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor::watt_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor/watt_msg";
  }

  static const char* value(const ::sensor::watt_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor::watt_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 定义一个4维向量用于传输功率的数据\n"
"float32 voltage\n"
"float32 current\n"
"float32 resistance\n"
"float32 watt\n"
;
  }

  static const char* value(const ::sensor::watt_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor::watt_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
      stream.next(m.current);
      stream.next(m.resistance);
      stream.next(m.watt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct watt_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor::watt_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor::watt_msg_<ContainerAllocator>& v)
  {
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
    s << indent << "resistance: ";
    Printer<float>::stream(s, indent + "  ", v.resistance);
    s << indent << "watt: ";
    Printer<float>::stream(s, indent + "  ", v.watt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MESSAGE_WATT_MSG_H
